version: '3.8'

services:
  db:
    image: postgres:15
    container_name: task_management_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: riddhi0117
      POSTGRES_DB: task_management_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: task_management_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=postgresql://postgres:riddhi0117@db:5432/task_management_app
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - EXP_TIME=30
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
